import streamlit as st
from docx import Document
from pptx import Presentation
import openai
import os

# --- Password Prompt (always appears) ---
password = st.text_input("Enter password to access the marking agent:", type="password")
if password != "Roxieandcleothecats1!":
    st.warning("Please enter the correct password to continue.")
    st.stop()

st.title("OCR and BTEC Marking Agent (AI-Powered)")

openai.api_key = st.secrets["OPENAI_API_KEY"] if "OPENAI_API_KEY" in st.secrets else os.getenv("OPENAI_API_KEY")

units = {
    "Unit 101 – Health and Safety in ICT": "unit101_knowledge.txt",
    "Unit 318 – Software Installation and Upgrade": "unit318_knowledge.txt",
    "Unit 22 – Big Data Analytics (OCR)": "unit22_knowledge.txt"
}

selected_unit = st.selectbox("Select unit to mark:", list(units.keys()))

def load_knowledge(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        return f.read()

knowledge = load_knowledge(units[selected_unit])

st.header(f"Knowledge Base for {selected_unit}")
st.text_area("Knowledge", knowledge, height=300)

uploaded_files = st.file_uploader(
    "Upload up to two files for the assignment (Word and/or PowerPoint)", 
    type=["docx", "pptx"], 
    accept_multiple_files=True
)

assignment_text = ""
if uploaded_files:
    st.success("Files uploaded!")
    for uploaded_file in uploaded_files:
        if uploaded_file.name.endswith(".docx"):
            doc = Document(uploaded_file)
            assignment_text += "\n".join([para.text for para in doc.paragraphs]) + "\n"
        elif uploaded_file.name.endswith(".pptx"):
            prs = Presentation(uploaded_file)
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text"):
                        assignment_text += shape.text + "\n"
    st.write("Combined assignment content preview:")
    st.text_area("Assignment Text", assignment_text, height=300)
    if st.button("Mark with AI"):
        with st.spinner("Marking..."):
            improved_prompt = f"""
You are an experienced OCR and BTEC assessor for {selected_unit} (Level 3).
Your role is to review the student's assignment strictly against the grading criteria and guidance provided in the knowledge file below.
Do not use the internet, external sources, or your own assumptions—only use the content of the knowledge file for all grading, definitions, and feedback.

{knowledge}

Assignment:
{assignment_text}

Instructions:
- For each learning outcome and assessment point, review the work against the Pass, Merit, and Distinction criteria as defined in the knowledge file.
- If the knowledge file does not contain Merit or Distinction criteria for a learning outcome or assessment point, do not grade or comment on those criteria. Only review and provide feedback for the criteria that are present in the knowledge file.
- If a criterion is ambiguous or missing from the knowledge file, state this and do not attempt to infer or fill gaps.
- For each criterion, state if it is fully met, partly met, or not met.
- Indicate which grading level is currently achievable based on the submitted work: Pass, Merit, or Distinction.
- If only Pass criteria are met, say the student is on track for a Pass. If Pass and Merit criteria are met, say they are on track for a Merit. If all criteria are met, say they are on track for a Distinction.
- If some criteria are missing or incomplete, advise what additional work is needed to reach the next grade.
- If the assignment is incomplete or handed in as a partial submission, review only what is present and give guidance for improvement and grade progression.
- If you suspect any examples, sections, or passages in the assignment have been generated by AI (such as ChatGPT, Copilot, or similar tools) and there is no reference or acknowledgement of AI use, flag this in your feedback. Remind the student that using AI-generated content without proper referencing is not allowed and may result in the work being rejected or not marked. Advise the student to reference any AI tools used and to ensure all work is their own.
- For each learning outcome, give one positive comment and one suggestion for improvement.
- Do not rewrite or summarise the assignment; only review and comment.
- Keep feedback under 500 words.
- Use UK English throughout.
- Use a friendly, supportive tone—imagine you’re chatting with the student and want them to feel confident and motivated.
- Avoid formal or academic language; be clear, encouraging, and down-to-earth.
- Use phrases like "Well done", "Great effort", "Keep going", "You’re nearly there", "Try adding...", "Next time, you could..."
- End with a brief summary stating what grade is currently achievable and encourage the student to keep improving.
- Always focus your feedback on the student’s improvement and next steps.
"""
            try:
                response = openai.chat.completions.create(
                    model="gpt-4.1-mini",
                    messages=[{"role": "user", "content": improved_prompt}],
                    max_tokens=800,
                    temperature=0.2,
                )
                feedback = response.choices[0].message.content
                st.header("AI-Powered Feedback")
                st.write(feedback)
            except openai.RateLimitError:
                st.error("OpenAI rate limit reached. Please wait and try again later, or check your usage at https://platform.openai.com/usage.")

st.info("This app is free to use. Select your unit, upload up to two assignment files, and view the knowledge base above.")